apiVersion: batch/v1
kind: Job
metadata:
  generateName: gamal-test-
spec:
  template:
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      restartPolicy: Never
